os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/swixbase/ciscript/master/ci-3.1)"
  - eval "$(curl -sL https://raw.githubusercontent.com/swixbase/ciscript/master/codecov)"